# Windows/DOS still in your muscle memory

alias chdir='pwd'
alias chkdsk='du -s'
alias cls='clear'
alias comp='diff'
alias copy='cp -piv'
alias del='rm'
alias deltree='rm -r'
alias dir='command ls -lSrah'
alias edit='code'
alias edlin='ed'
alias fc='comp'
alias help='man'
alias md='mkdir'
alias mem='free'
alias more='less'
alias move='mv -iv'
alias nbtstat='nslookup'
alias pkzip='zip'
alias print='lpr'
alias rd='rmdir'
alias ren='mv'
alias tasklist='top'
alias tracert='traceroute'
alias type='cat'
alias ver='uname -a'
alias xcopy='cp -R'