# fix typoes

alias brwe='brew'
alias chomd="chmod"
alias coed='code'
alias dior='dir'
alias dire='dir'
alias dor='dir'
alias die='dir'
alias doe='dir'
alias dur='dir'
alias emcas='emacs'
alias grpe='grep'
alias mroe='more'
alias pcio='pico'
alias pciop='pico'
alias pin='pine'
alias pnie='pine'
alias pre='more'
alias puthon='puthon'
alias rbuy='ruby'
alias sduo='sudo'   
alias sl='ls'
alias srln='slrn'                                                                                                                           
alias suod='sudo' 
