# fix typoes

alias alais='alias'
alias brwe='brew'
alias chomd="chmod"
alias coed='code'
alias dior='dir'
alias dire='dir'
alias dor='dir'
alias die='dir'
alias doe='dir'
alias dur='dir'
alias emcas='emacs'
alias grpe='grep'
alias mann='man'
alias mroe='more'
alias puthon='python'
alias rbuy='ruby'
alias sduo='sudo'   
alias sl='ls'                                                                                                                         
alias suod='sudo' 
