# fix typoes

alias dior='dir'
alias dire='dir'
alias dor='dir'
alias die='dir'
alias doe='dir'
alias dur='dir'
alias mroe='more'
alias pcio='pico'
alias pciop='pico'
alias pin='pine'
alias pnie='pine'
alias ,pre='more'
alias sl='ls'
alias srln='slrn'
alias grpe='grep'
alias brwe='brew'
alias puthon='puthon'
alias rbuy='ruby'
alias coed='code'
alias chomd="chmod"
alias sl='ls'                                                                                                                                                              
alias sduo='sudo'                                                                                                                                               
alias suod='sudo' 
alias emcas='emacs'
